"""
Planner-Executor Integration
=============================

Integrates the conversation layer with the existing planner-executor architecture.

ARCHITECTURE:
```
┌─────────────────────────────────────────────────────────────────────┐
│                         USER INTERFACE                              │
│                    (Voice / Tray / Dialog)                          │
└────────────────────────────┬────────────────────────────────────────┘
                             │
                             ▼
┌─────────────────────────────────────────────────────────────────────┐
│                    DIALOGUE FLOW CONTROLLER                         │
│  ┌─────────────────────────────────────────────────────────────┐   │
│  │              ConversationManager                             │   │
│  │  • Intent Classification                                     │   │
│  │  • Entity Extraction                                         │   │
│  │  • State Management                                          │   │
│  │  • Confirmation Handling                                     │   │
│  └─────────────────────────────────────────────────────────────┘   │
└────────────────────────────┬────────────────────────────────────────┘
                             │
          ┌──────────────────┴──────────────────┐
          │                                     │
          ▼                                     ▼
┌────────────────────┐               ┌────────────────────┐
│      PLANNER       │               │     EXECUTOR       │
│  (Local LLM)       │               │  (Action Runner)   │
│                    │               │                    │
│  • Task breakdown  │──────────────▶│  • open_url        │
│  • Action planning │  ActionPlan   │  • search_web      │
│  • Context-aware   │               │  • read_file       │
│                    │               │  • calculate       │
└────────────────────┘               └────────────────────┘
          │                                     │
          ▼                                     ▼
┌────────────────────┐               ┌────────────────────┐
│   LOCAL LLM        │               │   PERMISSION       │
│   (Ollama)         │               │   GUARD            │
│                    │               │                    │
│  • Phi-3-mini      │               │  • Action whitelist│
│  • Mistral-7B      │               │  • Risk assessment │
│  • No cloud        │               │  • Audit logging   │
└────────────────────┘               └────────────────────┘
```

INTEGRATION POINTS:
1. DialogueFlowController receives user input
2. ConversationManager classifies intent and extracts entities
3. If action needed: Planner creates action plan
4. If confirmed: Executor runs the action
5. Response flows back through DialogueFlowController
"""

from typing import Dict, Any, Optional, Callable, Awaitable
from dataclasses import dataclass
from enum import Enum

from .state_model import ConversationManager, IntentType, PendingAction
from .dialogue_flow import DialogueFlowController, DialogueResponse


class ActionType(Enum):
    """Supported action types for the executor."""
    OPEN_URL = "open_url"
    SEARCH_WEB = "search_web"
    READ_FILE = "read_file"
    CALCULATE = "calculate"
    EXPLAIN = "explain"
    STUDY_PLAN = "study_plan"
    SEND_NOTIFICATION = "send_notification"
    SPEAK = "speak"


@dataclass
class ActionPlan:
    """
    A plan generated by the planner for execution.
    
    SAFETY PROPERTIES:
    - requires_confirmation: If True, MUST get user approval
    - is_reversible: If True, action can be undone
    - risk_level: low/medium/high affects confirmation stringency
    """
    action_type: ActionType
    parameters: Dict[str, Any]
    description: str                    # Human-readable description
    requires_confirmation: bool = True  # Almost always True
    is_reversible: bool = True
    risk_level: str = "low"
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_type": self.action_type.value,
            "parameters": self.parameters,
            "description": self.description,
            "requires_confirmation": self.requires_confirmation,
            "is_reversible": self.is_reversible,
            "risk_level": self.risk_level,
        }


class Planner:
    """
    Plans actions based on user intent and context.
    
    RESPONSIBILITIES:
    1. Take classified intent and entities
    2. Generate an ActionPlan
    3. Use LLM for complex planning (multi-step tasks)
    
    DOES NOT:
    - Execute actions
    - Make confirmation decisions
    - Modify system state
    """
    
    # Direct intent-to-action mappings (no LLM needed)
    DIRECT_MAPPINGS = {
        IntentType.OPEN_URL: ActionType.OPEN_URL,
        IntentType.SEARCH_WEB: ActionType.SEARCH_WEB,
        IntentType.READ_FILE: ActionType.READ_FILE,
        IntentType.CALCULATE: ActionType.CALCULATE,
        IntentType.EXPLAIN: ActionType.EXPLAIN,
        IntentType.STUDY_PLAN: ActionType.STUDY_PLAN,
    }
    
    def __init__(self, llm_callback: Optional[Callable] = None):
        """
        Initialize planner.
        
        Args:
            llm_callback: Optional LLM for complex planning
        """
        self._llm = llm_callback
    
    async def plan(
        self,
        intent: IntentType,
        entities: Dict[str, Any],
        context: str = "",
    ) -> Optional[ActionPlan]:
        """
        Generate an action plan from intent and entities.
        
        Args:
            intent: Classified user intent
            entities: Extracted entities from user input
            context: Conversation context for multi-turn
        
        Returns:
            ActionPlan or None if no action needed
        """
        # Check for direct mapping
        if intent in self.DIRECT_MAPPINGS:
            action_type = self.DIRECT_MAPPINGS[intent]
            
            return ActionPlan(
                action_type=action_type,
                parameters=self._build_parameters(action_type, entities),
                description=self._build_description(action_type, entities),
            )
        
        # For complex intents, use LLM if available
        if self._llm:
            return await self._plan_with_llm(intent, entities, context)
        
        return None
    
    def _build_parameters(
        self, 
        action_type: ActionType, 
        entities: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Build action parameters from entities."""
        if action_type == ActionType.OPEN_URL:
            return {
                "url": entities.get("url", ""),
                "site_name": entities.get("site", ""),
            }
        
        if action_type == ActionType.SEARCH_WEB:
            return {
                "query": entities.get("query", ""),
                "engine": entities.get("engine", "google"),
            }
        
        if action_type == ActionType.READ_FILE:
            return {
                "file_path": entities.get("file_path", ""),
                "operation": entities.get("operation", "summarize"),
            }
        
        if action_type == ActionType.CALCULATE:
            return {
                "expression": entities.get("expression", ""),
            }
        
        if action_type == ActionType.EXPLAIN:
            return {
                "topic": entities.get("topic", ""),
                "level": entities.get("level", "undergraduate"),
            }
        
        return entities
    
    def _build_description(
        self, 
        action_type: ActionType, 
        entities: Dict[str, Any]
    ) -> str:
        """Build human-readable description."""
        if action_type == ActionType.OPEN_URL:
            site = entities.get("site", entities.get("url", "website"))
            return f"open {site} in your browser"
        
        if action_type == ActionType.SEARCH_WEB:
            query = entities.get("query", "")
            return f"search the web for '{query}'"
        
        if action_type == ActionType.READ_FILE:
            file = entities.get("file_path", "file")
            return f"read and summarize {file}"
        
        if action_type == ActionType.CALCULATE:
            expr = entities.get("expression", "expression")
            return f"calculate {expr}"
        
        if action_type == ActionType.EXPLAIN:
            topic = entities.get("topic", "topic")
            return f"explain {topic}"
        
        return f"perform {action_type.value}"
    
    async def _plan_with_llm(
        self,
        intent: IntentType,
        entities: Dict[str, Any],
        context: str,
    ) -> Optional[ActionPlan]:
        """Use LLM for complex multi-step planning."""
        if not self._llm:
            return None
        
        # Build prompt for LLM
        prompt = f"""
        You are a task planner for a desktop assistant.
        
        User Intent: {intent.value}
        Entities: {entities}
        Conversation Context: {context}
        
        Generate a simple action plan. Respond in JSON:
        {{
            "action": "action_type",
            "parameters": {{}},
            "description": "what you'll do"
        }}
        
        Available actions: open_url, search_web, read_file, calculate, explain
        """
        
        try:
            response = await self._llm(prompt)
            # Parse LLM response and create ActionPlan
            # (Implementation depends on LLM response format)
            return None  # Placeholder
        except Exception:
            return None


class Executor:
    """
    Executes approved action plans.
    
    SAFETY GUARANTEES:
    1. Only executes APPROVED actions
    2. All actions are audited
    3. Only whitelisted actions allowed
    4. No network actions without confirmation
    
    PERMISSION MODEL:
    - open_url: Allowed (opens in user's browser)
    - search_web: Allowed (opens search in browser)
    - read_file: Allowed for user-owned files
    - calculate: Always allowed (local computation)
    - explain: Always allowed (local LLM)
    - file_write: NEVER allowed
    - system_command: NEVER allowed
    """
    
    # Whitelisted action handlers
    ALLOWED_ACTIONS = {
        ActionType.OPEN_URL,
        ActionType.SEARCH_WEB,
        ActionType.READ_FILE,
        ActionType.CALCULATE,
        ActionType.EXPLAIN,
        ActionType.STUDY_PLAN,
        ActionType.SEND_NOTIFICATION,
        ActionType.SPEAK,
    }
    
    # Actions that NEVER require confirmation (safe)
    AUTO_CONFIRM = {
        ActionType.SPEAK,
        ActionType.SEND_NOTIFICATION,
    }
    
    def __init__(self):
        self._handlers: Dict[ActionType, Callable] = {}
        self._audit_log = []
    
    def register_handler(
        self, 
        action_type: ActionType, 
        handler: Callable[..., Awaitable[Dict[str, Any]]]
    ) -> None:
        """Register a handler for an action type."""
        if action_type in self.ALLOWED_ACTIONS:
            self._handlers[action_type] = handler
    
    async def execute(self, plan: ActionPlan) -> Dict[str, Any]:
        """
        Execute an approved action plan.
        
        Returns:
            {"success": bool, "result": Any, "error": str}
        """
        # Check if action is allowed
        if plan.action_type not in self.ALLOWED_ACTIONS:
            self._log_audit(plan, success=False, reason="Action not allowed")
            return {
                "success": False,
                "error": f"Action '{plan.action_type.value}' is not allowed",
            }
        
        # Check if handler exists
        if plan.action_type not in self._handlers:
            self._log_audit(plan, success=False, reason="No handler")
            return {
                "success": False,
                "error": f"No handler for '{plan.action_type.value}'",
            }
        
        # Execute
        try:
            handler = self._handlers[plan.action_type]
            result = await handler(**plan.parameters)
            self._log_audit(plan, success=True)
            return {
                "success": True,
                "result": result,
            }
        except Exception as e:
            self._log_audit(plan, success=False, reason=str(e))
            return {
                "success": False,
                "error": str(e),
            }
    
    def _log_audit(
        self, 
        plan: ActionPlan, 
        success: bool, 
        reason: str = ""
    ) -> None:
        """Log action execution for audit trail."""
        from datetime import datetime
        
        entry = {
            "timestamp": datetime.now().isoformat(),
            "action": plan.action_type.value,
            "parameters": plan.parameters,
            "success": success,
            "reason": reason,
        }
        self._audit_log.append(entry)
        
        # Keep only last 100 entries
        if len(self._audit_log) > 100:
            self._audit_log.pop(0)
    
    def get_audit_log(self) -> list:
        """Get recent audit log entries."""
        return self._audit_log.copy()


class IntegratedAssistant:
    """
    The main integrated assistant combining all layers.
    
    This is the top-level class that:
    1. Receives user input (text or voice)
    2. Routes through DialogueFlowController
    3. Uses Planner for action planning
    4. Uses Executor for action execution
    5. Returns responses (text and/or speech)
    
    USAGE:
    ```python
    assistant = IntegratedAssistant()
    
    # Register action handlers
    assistant.register_action(ActionType.OPEN_URL, open_url_handler)
    assistant.register_action(ActionType.SEARCH_WEB, search_web_handler)
    
    # Process user input
    response = await assistant.process("open youtube")
    print(response.text)  # "I'll open YouTube. Should I proceed?"
    
    response = await assistant.process("yes")
    print(response.text)  # "Done! Opened YouTube."
    ```
    """
    
    def __init__(self, llm_callback: Optional[Callable] = None):
        self.planner = Planner(llm_callback)
        self.executor = Executor()
        self.dialogue = DialogueFlowController(
            planner_callback=self._plan,
            executor_callback=self._execute,
        )
    
    def register_action(
        self, 
        action_type: ActionType, 
        handler: Callable[..., Awaitable[Dict[str, Any]]]
    ) -> None:
        """Register an action handler."""
        self.executor.register_handler(action_type, handler)
    
    async def process(self, user_input: str) -> DialogueResponse:
        """
        Process user input and return response.
        
        This is the main entry point.
        """
        return await self.dialogue.handle_input(user_input)
    
    async def _plan(
        self, 
        intent: IntentType, 
        entities: Dict[str, Any]
    ) -> Optional[ActionPlan]:
        """Internal: Create action plan."""
        context = self.dialogue.get_conversation_context()
        return await self.planner.plan(intent, entities, context)
    
    async def _execute(
        self, 
        action_type: str, 
        parameters: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Internal: Execute action."""
        try:
            at = ActionType(action_type)
        except ValueError:
            return {
                "success": False,
                "error": f"Unknown action type: {action_type}",
            }
        
        plan = ActionPlan(
            action_type=at,
            parameters=parameters,
            description="",
        )
        
        return await self.executor.execute(plan)
    
    def reset_conversation(self) -> str:
        """Reset conversation state. Returns new session ID."""
        return self.dialogue.reset()
    
    def get_audit_log(self) -> list:
        """Get executor audit log."""
        return self.executor.get_audit_log()
